site_name: Template
site_dir: out/doc

nav:
  - Home: 'index.md'
  - 'User':
    - 'User Guide': 'User/Guide/index.md'
    - 'User Manual': 'User/Manual/index.md'
  - 'Developer':
    - 'Class Description': 'Developer/ClassDescription/index.md'
    - 'System Description': 'Developer/SystemDescription/index.md'

markdown_extensions:
  - plantuml_markdown
  - toc:
      permalink: "#"
      baselevel: 1
      toc_depth: "2-3"
      separator: "-"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - macros
  - search

theme:
  name: material
  navigation_depth: 4
  features:
    - content.code.annotate